const data = {
  products: [
    {
      name: 'Tacos de Pastor',
      seller:'5fc86b33608c7756480a015e',
      category: 'Tacos',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Khalifa',
      rating: 4.5,
      numReviews: 10,
      description: 'Ricos tacos',
    },
    {
      name: 'Gaban Licenciado Valeriano',
      seller:'5fc86b33608c7756480a015e',
      category: 'Gaban',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Licenciado Valeriano',
      rating: 4.0,
      numReviews: 10,
      description: 'Pal frio',
    },
    {
      name: 'Tacos de Lengua',
      seller:'5fc86b33608c7756480a015e',
      category: 'Tacos',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Esquina',
      rating: 4.8,
      numReviews: 17,
      description: 'Ricos tacos, chance te da chorro',
    },
    {
      name: 'Tequila Don Julio',
      seller:'5fc86b33608c7756480a015e',
      category: 'Tequila',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Don Julio',
      rating: 4.5,
      numReviews: 14,
      description: 'Best Tequila 100/10',
    },
    {
      name: 'Tequila 7 leguas',
      seller:'5fc86b33608c7756480a015e',
      category: 'Tequila',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: '7 leguas',
      rating: 4.5,
      numReviews: 10,
      description: 'Excelente tequila',
    },
    {
      name: 'Gaban OG',
      seller:'5fc86b33608c7756480a015e',
      category: 'Gaban',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'N.A',
      rating: 4.5,
      numReviews: 15,
      description: 'Hecho por algun cristiano en Oaxaca',
    },
  ],
};
export default data;
